### ISSUE TITLE
TypeError running simple message on windows

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-incubator/conda-suggest#1]
I'm getting a `TypeError` when trying to test this cool new tool on Windows:

<details>
<summary>Conda create</summary>

```
❯ conda create -n conda-suggest conda-suggest
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\spxdmm\Miniconda3\envs\conda-suggest

  added / updated specs:
    - conda-suggest



  certifi            conda-forge/win-64::certifi-2020.6.20-py38h32f6830_0
  conda-suggest      conda-forge/noarch::conda-suggest-0.1.0-pyh9f0ad1d_0
  conda-suggest-con~ conda-forge/win-64::conda-suggest-conda-forge-2020.9.1-0
  openssl            conda-forge/win-64::openssl-1.1.1g-he774522_1
  pip                conda-forge/noarch::pip-20.2.2-py_0
  python             conda-forge/win-64::python-3.8.5-h60c2a47_7_cpython
  python_abi         conda-forge/win-64::python_abi-3.8-1_cp38
  setuptools         conda-forge/win-64::setuptools-49.6.0-py38h32f6830_0
  sqlite             conda-forge/win-64::sqlite-3.33.0-he774522_0
  tqdm               conda-forge/noarch::tqdm-4.48.2-pyh9f0ad1d_0
  vc                 conda-forge/win-64::vc-14.1-h869be7e_1
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.16.27012-h30e32a0_2
  wheel              conda-forge/noarch::wheel-0.35.1-pyh9f0ad1d_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py38_1003


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate conda-suggest
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
</details>

```pytb
❯ conda suggest message gwpy-plot
Traceback (most recent call last):
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\Scripts\conda-suggest-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\lib\site-packages\conda_suggest\main.py", line 27, in main
    find.message(ns.exe)
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\lib\site-packages\conda_suggest\find.py", line 135, in message
    s = message_string(exe, conda_suggest_path=conda_suggest_path)
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\lib\site-packages\conda_suggest\find.py", line 115, in message_string
    exact = exact_find(exe, conda_suggest_path=conda_suggest_path)
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\lib\site-packages\conda_suggest\find.py", line 92, in exact_find
    finds |= exact_find_in_mapfile(exe, filename)
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\lib\site-packages\conda_suggest\find.py", line 84, in exact_find_in_mapfile
    return {(mapfile.channel, mapfile.subdir, e, p) for e, p in mapfile.exact_find(exe)}
  File "C:\Users\spxdmm\Miniconda3\envs\conda-suggest\lib\site-packages\conda_suggest\find.py", line 48, in exact_find
    return self.exact_find(exe + ".exe") | self.exact_find(exe + ".bat")
TypeError: unsupported operand type(s) for |: 'list' and 'set'

**Comment by scopatz** [comment]
Thanks for reporting this! It has been fixed in e199915
